name: build

on:
  push:
    branches: [ develop ]
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x, 14.x, 15.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: typing / install deps
        run: npm ci
        working-directory: typing
      - name: typing / lint
        run: npm run lint
        working-directory: typing
      - name: typing / check style
        run: npm run format-check
        working-directory: typing

      - name: example / install deps
        run: npm ci
        working-directory: example
      - name: example / lint
        run: npm run lint
        working-directory: example
      - name: example / check style
        run: npm run format-check
        working-directory: example
      - name: example / build
        run: npm run build
        working-directory: example
