name: release

on:
  release:
    types: [created]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: 12

      - name: typing / install deps
        run: npm ci
        working-directory: typing
      - name: typing / lint
        run: npm run lint
        working-directory: typing
      - name: typing / check style
        run: npm run format-check
        working-directory: typing

      - name: example / install deps
        run: npm ci
        working-directory: example
      - name: example / lint
        run: npm run lint
        working-directory: example
      - name: example / check style
        run: npm run format-check
        working-directory: example
      - name: example / build
        run: npm run build
        working-directory: example

  publish-npm:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/
      - run: npm ci
        working-directory: typing
      - run: npm publish
        working-directory: typing
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}

  publish-gpr:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://npm.pkg.github.com/
      - run: npm ci
        working-directory: typing
      - run: npm publish
        working-directory: typing
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
